### ISSUE TITLE
doc request

### ISSUE THREAD

**Issue by radzhome** [wolfg1969/elastic-beanstalk-nginx-uwsgi-django#1]
hey can you add doc on what AMI to use for this?  I know there are issues with the new Amazon Linux AMIs and geodjango support. The 2013.09 instances worked fine.

**Comment by wolfg1969** [comment]
I only test this with 64bit Amazon Linux 2013.09 running Python 2.7.

**Comment by radzhome** [comment]
Yeah that is the only one that works for me with geodjango, the new one I
can't install gdal on.

I noticed the ami's act differently from account to account though. Any
ideas why? I mean the same ami on an older account uses yum repo 2013.09,
the newer account, same ami, same deploy but uses 2014.09 repo in yum.conf
. There are like some hidden settings in the Beanstalk account or something
I think.

**Comment by radzhome** [comment]
BTW. did you try the EB CLI 2.6.x or 3.0X ? I used them and wasn't very
happy with either. Thinking of re-writing the deploy function myself. The
other functionality in 3.x is great.

**Comment by wolfg1969** [comment]
@radlws Sorry, I don't play with EB much recently. The production instances works well, you know. When I deploy new projects on EB I will test this again. Thanks a lot for your information about the AMI and EB CLI.

**Comment by thisiscam** [comment]
Just coming to the issue that I can't figure out a way to deploy geodjango onto elasticbeanstalk... Is it because I'm using 2014.09 Image? Or has there been any updates on this issue? 
For me now, I followed the guide here http://www.daveoncode.com/2014/02/18/creating-custom-ami-with-postgis-and-its-dependencies-to-deploy-django-geodjango-amazon-elastic-beanstalk/; but after deploying to elastic beanstalk with my configured AMI, the events says "Enviroment update completes but with errors", and I can't pull any logs from either amazon console or eb logs. Is this the same behavior when you said "issues with the new Amazon Linux AMIs and geodjango support."?

**Comment by radzhome** [comment]
Try this out: https://github.com/radlws/django-awseb-tasks

Also this: http://stackoverflow.com/questions/27177327/setting-up-django-with-geodjango-support-in-aws-beanstalk-or-ec2-instance

That works for me, no need to compile anything from source.

**Comment by wolfg1969** [comment]
UPDATE: works on 64bit Amazon Linux 2014.09 v1.2.0 running Python 2.7
